### ISSUE TITLE
intial value of option "backgroundColor" is not respected

### ISSUE THREAD

**Issue by hrbu** [iCubbles/wordcloud2-wrapper#1]
I tried to initialize a `"wordcloud-default"` component instance with the `"backgroundColor"` option. The value is not respected when the instance is rendered intially. Setting the `"options"` slot again with the same value (using the "cubbles-webinspector:0.6") works as expected. Same with the options `"fontFamily"` and `"color"`.

_Interesting: Setting the options `"shuffle"` and `"rotateRatio"` initially works as expected._

See https://output.jsbin.com/fiheqoh to repoduce the issue.

**Comment by edwingamboa** [comment]
Related ticket: https://cubbles.atlassian.net/browse/CUBBLES-118
